### ISSUE TITLE
What to do when a package is not dune-compatible

### ISSUE THREAD

**Issue by TheLortex** [avsm/duniverse#19]
When using `duniverse` on a mirage unikernel, a lot of base layer packages remain non-dune. These packages (`solo5`, `solo5-bindings-hvt`, `ocaml-freestanding`, `minios-xen`, ..) are quite a hard work to port to dune, and probably other problems will arise.
In the short term, I propose to keep track of them, and allow to install them using a `duniverse opam-install` command for example.

**Comment by NathanReb** [comment]
Maybe as a short term solution, `duniverse` should build a local switch and install them there instead of installing them to a global switch.

**Comment by NathanReb** [comment]
A fix to this should also resolve the issue you raised in #14

**Comment by TheLortex** [comment]
Having a local switch implies to build local ocaml compiler ? This seems a bit heavy, I wouldn't mind installing the packages in the current global switch.

**Comment by NathanReb** [comment]
I believe we can close this now!
