### ISSUE TITLE
Duniverse gets confused when a package no longer needs the duniverse overlay

### ISSUE THREAD

**Issue by jonludlam** [avsm/duniverse#3]
When a package used to need a duniverse fork but no longer does (e.g. hannesm/duration) the tool gets confused and tries to check out a non-existant branch from the duniverse fork.

**Comment by hannesm** [comment]
in https://github.com/dune-universe/ the two repositories "duration" and "randomconv" should be removed (both have opam-repo released dune versions). also, once https://github.com/ocaml/opam-repository/pull/13806 is merged, the "ocaml-x509" repository should be removed as well. :)

**Comment by avsm** [comment]
I've removed those three, thanks @hannesm.

The solution to this one is to remove config.ml entirely and replace it with an opam remote. @NathanReb is looking into this.

**Comment by hannesm** [comment]
some more repositories which shouldn't be in dune-universe anymore (since they're now released to opam-repository using dune)
- https://github.com/dune-universe/ocaml-x509
- https://github.com/dune-universe/psq
- https://github.com/dune-universe/lru

**Comment by NathanReb** [comment]
I think that with `duniverse` now relying on [dune-uiverse/opam-overlays](https://github.com/dune-universe/opam-overlays) to find dune ports this is fixed now.

@hannesm can you confirm that when you use the latest `duniverse` the dunified upstream version is now picked?

**Comment by hannesm** [comment]
@NathanReb I'll try to get the latest `duniverse` up and running over Easter, thanks! :)

**Comment by avsm** [comment]
Almost fixed -- we should delete the old forks, or it'll get confusing with inactive ones.  That'll break old duniverse pulls, but that's ok -- it's never been released stably.

**Comment by NathanReb** [comment]
Should we delete the old forks?

Some opam-overlays packages depend on them so if we delete the forks we should also remove the corresponding package definition on the repo.

Isn't there some value in keeping them up for a little while? It might not be the case for those specific packages but I can definitely see it break some people's builds if they depend on a package with an upper bound if the new upstream dunified version exceeds that bound and we remove the dune ports of the previous versions.

**Comment by avsm** [comment]
We should delete the old forks. I've explained this and sorted it out in https://github.com/dune-universe/opam-overlays/pull/12
